<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>MushroomPropagator_Automate</AssemblyName>
    <RootNamespace>MushroomPropagator_Automate</RootNamespace>
    <Version>2.3.0</Version>
	  <TargetFramework>net6.0</TargetFramework>
    <IgnoreModFilePatterns>MushroomPropagator.dll</IgnoreModFilePatterns>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MushroomPropagator\MushroomPropagator.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Automate">
      <HintPath>$(GamePath)\Mods\Automate\Automate.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>